services:
  db:
    image: neo4j:4.4.15-community
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      internal:
        ipv4_address: 172.24.0.10
    volumes:
      - ./neo4j_mount/data:/data
      - ./neo4j_mount/logs:/logs
      - ./neo4j_mount/conf:/conf
    environment:
      - NEO4J_AUTH=neo4j/test
    deploy:
      resources:
        limits:
          memory: 3g

  app:
    image: neo4jtp:latest
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - ./db.json:/file.json
    environment:
      - JSON_FILE=/file.json
      - CLEANED_FILE=/file_cleaned.json
      - MAX_NODES=20000
      - NEO4J_IP=172.24.0.10 # must be the same as above
    deploy:
      resources:
        limits:
          memory: 4g

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: "172.24.0.0/24"
